site_name: Haskell funcstream
nav:
    - Home: index.md
    - About: about.md
    - Books: books.md
    - Talks: talks.md
    - Online-lectures: online-lectures.md
    - Blogs: blogs.md
    - Papers: papers.md
    - Code: code.md
    - Categories: categories.md
    - Observations: observations.md
theme: material

name: Deploy MkDocs
uses: mhausenblas/mkdocs-deploy-gh-pages@1.12
